title: Cyber Security Club at UC Davis
description: A webpage for Cyber Security Club at UC Davis. 
root: /
plugins:
  - jekyll-feed
  - jekyll-redirect-from
permalink: pretty
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
collections:
  notes:
    output: true
exclude:
 - /README.md
